module.exports = {
  version: 1,
  categories: [
    { key: "ticketDesk", name: "Ticket Desk" },
    { key: "intros", name: "Intros" },
    { key: "general", name: "General" },
    { key: "hangouts", name: "Hangouts" },
    { key: "voice", name: "Voice" },
    { key: "nsfw", name: "NSFW", accessRole: "NSFW Kink Channel Access" },
    { key: "games", name: "Games", accessRole: "Bot Games Channels" },
  ],

  channels: [
    { key: "starboard", name: "starboard", type: 0 },

    { key: "supportTickets", name: "support-tickets", type: 0, parent: "ticketDesk", readOnly: true },

    { name: "introduce-yourself", type: 0, parent: "intros" },
    { key: "roles", name: "roles", type: 0, parent: "intros", readOnly: true },
    { name: "rules", type: 0, parent: "intros", readOnly: true },
    { name: "town-uhaul", type: 0, parent: "intros" },

    { name: "gen-announcements", type: 0, parent: "general", readOnly: true },
    { name: "gen-birthdays", type: 0, parent: "general" },
    { name: "gen-chat", type: 0, parent: "general" },
    { name: "gen-dating-advice", type: 0, parent: "general" },
    { name: "the-turf-wars", type: 0, parent: "general" },

    { name: "anon-confessions", key: "confessions", type: 0, parent: "hangouts" },
    { name: "arcade", type: 0, parent: "hangouts" },
    { name: "book-club", key: "bookClub", type: 0, parent: "hangouts", launcher: "book" },
    { name: "clips-and-videos", type: 0, parent: "hangouts" },
    { name: "cliterary-society", type: 0, parent: "hangouts" },
    { name: "divigaytion", type: 0, parent: "hangouts" },
    { name: "doof-and-recipes", type: 0, parent: "hangouts" },
    { name: "drip-depot🔥", type: 0, parent: "hangouts" },
    { name: "dyke-digest", type: 0, parent: "hangouts", accessRole: "Dyke Digest Channel Access" },
    { name: "fun-n-games", type: 0, parent: "hangouts" },
    { name: "hellth", type: 0, parent: "hangouts" },
    { name: "help-me-adult", type: 0, parent: "hangouts" },
    { name: "hobbies", type: 0, parent: "hangouts" },
    { name: "ink-stained-wretches", key: "writing", type: 0, parent: "hangouts", launcher: "writing" },
    { name: "memes", type: 0, parent: "hangouts" },
    { name: "mental-health-positivity-blast", type: 0, parent: "hangouts" },
    { name: "movies-and-tv-shows", type: 0, parent: "hangouts" },
    { name: "music-talk", type: 0, parent: "hangouts" },
    { name: "photos", type: 0, parent: "hangouts" },
    { name: "plants", type: 0, parent: "hangouts" },
    { name: "question-of-the-gay", type: 0, parent: "hangouts" },
    { name: "selfies", type: 0, parent: "hangouts" },
    { name: "show-the-ink", type: 0, parent: "hangouts" },
    { name: "show-us-your-pets", type: 0, parent: "hangouts" },
    { name: "sports", type: 0, parent: "hangouts" },
    { name: "travel-gaygency", type: 0, parent: "hangouts" },
    { name: "ugh-vent-here", type: 0, parent: "hangouts" },

    { name: "gayming", type: 2, parent: "voice" },
    { name: "general", type: 2, parent: "voice" },

    { name: "chatting", type: 0, parent: "nsfw", nsfw: true },
    { name: "high-thoughts", type: 0, parent: "nsfw", nsfw: true },
    { name: "nsfw-confessions", type: 0, parent: "nsfw", nsfw: true },
    { name: "nsfw-memes", type: 0, parent: "nsfw", nsfw: true },
    { name: "nsfw-selfies", type: 0, parent: "nsfw", nsfw: true },
    { name: "the-dungeon", type: 0, parent: "nsfw", nsfw: true },

    { name: "catch-pokemon", type: 0, parent: "games" },
    { name: "card-against-gays", type: 0, parent: "games" },
    { name: "counting-bitches", type: 0, parent: "games" },
    { name: "grow-our-tree", type: 0, parent: "games" },
    { name: "ihop-parking-lot", type: 0, parent: "games" },
    { name: "owo-nonsense", type: 0, parent: "games" },
    { name: "taco-shack", type: 0, parent: "games" },
    { name: "trivia", type: 0, parent: "games" },
    { name: "walmart-parking-lot", type: 0, parent: "games" },
    { name: "wordle", type: 0, parent: "games" },
  ],

  roleGroups: [
    { key: "colors", title: "🎨 Pick Your Color", exclusive: true, roles: [
      ["🔴","Red",0xe74c3c],["🟠","Orange",0xe67e22],["🟡","Yellow",0xf1c40f],["🔵","Blue",0x3498db],
      ["🟢","Green",0x2ecc71],["🟣","Purple",0x9b59b6],["🩷","Pink",0xff8fab],["🩵","Teal",0x3fc1c9],
      ["🌊","Sea Foam Green",0x9fe2bf],["☕","Coffee",0x6f4e37],["🤎","Orange Brown",0xa0522d],["🧱","Maroon",0x800000],
      ["🌌","Dark Blue",0x1f3a93],["🌼","Pale Yellow",0xfff2a8],["🩶","Grey",0x95a5a6],["🌿","Sage Green",0x9caf88]
    ]},
    { key: "age", title: "🎂 Age", exclusive: true, roles: [["🐣","22–25"],["🐥","26–30"],["🐤","31–35"],["🍗","36–40"],["🍽️","41+"]] },
    { key: "dm", title: "💌 Direct Messages", exclusive: true, roles: [["😸","DMs Open"],["🦉","Ask to DM"],["🙀","DMs Closed"]] },
    { key: "pronouns", title: "🏳️ Pronouns", exclusive: true, roles: [["👩","She/Her"],["🕵️","They/Them"],["🦙","Ask Me"]] },
    { key: "relationship", title: "❤️ Relationship Status", exclusive: true, roles: [["🎲","Single"],["🥸","Taken"],["🐸","It's Complicated"],["🐑","Poly Open"],["📫","Poly Closed"]] },
    { key: "timezone", title: "🌍 Timezone", exclusive: false, roles: [["❤️","CST"],["🧡","EST"],["💛","MST"],["💚","PST"],["🩵","GMT +1"],["💜","GMT +7"]] },
    { key: "pings", title: "📣 Ping Roles", exclusive: false, roles: [["🎮","Gaming"],["🎬","Movies"],["💬","Chat"]] },
    { key: "access", title: "🚪 Channel Access", exclusive: false, roles: [["⛓️","NSFW Kink Channel Access"],["🌿","420 Friendly"],["🤖","Bot Games Channels"],["🐸","Dyke Digest Channel Access"],["🗳️","Current Events / Politics"]] },
    { key: "events", title: "📅 Event Pings", exclusive: false, roles: [["✈️","Server Meet Up Ping"],["🪱","Bookworm"]] },
    { key: "gaming", title: "🎮 Gaming Pings", exclusive: false, roles: [["🥴","COD"],["🪖","Fortnite"],["🦉","Palworld"],["🌽","Stardew"],["👹","Multiplayer"],["👀","Gaming Voyeur"],["😂","Fall Guys"],["🃏","Cards Against Humanity"]] },
    { key: "affiliation", title: "🏴 Choose Your Affiliation", exclusive: true, roles: [["🐦‍⬛","Crow Cartel"],["🐕","Public Menaces"],["🐱","Cat Burglars"],["✨","Glitter Gang"],["⛓️","Dungeon Denizens"]] },
  ],

  launchers: [
    { key: "ticket", label: "Support Ticket", channel: "supportTickets", category: "ticketDesk", emoji: "🎫", private: true, prefix: "ticket", maxOpenPerUser: 1, staffRoles: ["Moderator","Admin"] },
    { key: "book", label: "Book Club Discussion", channel: "bookClub", category: "hangouts", emoji: "📖", private: false, prefix: "book", maxOpenPerUser: 3 },
    { key: "writing", label: "Writing Discussion", channel: "writing", category: "hangouts", emoji: "📝", private: false, prefix: "writing", maxOpenPerUser: 5 },
  ],

  starboard: { channel: "starboard", emoji: "⭐", threshold: 3 },
  confessions: { channel: "confessions", retainAuthor: true },
};
